// Generated by Apple Swift version 1.2 (swiftlang-602.0.53.1 clang-602.0.53)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import CoreLocation;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface CLLocation (SWIFT_EXTENSION(SenseSdk))
@end


SWIFT_CLASS("_TtC8SenseSdk8Cooldown")
@interface Cooldown : NSObject
@end

@class Location;
@class NSMutableDictionary;
@class NSCoder;

SWIFT_CLASS("_TtC8SenseSdk14CustomGeofence")
@interface CustomGeofence : NSObject <NSCoding>
@property (nonatomic, readonly) Location * __nonnull location;
@property (nonatomic, readonly) double radius;
@property (nonatomic, readonly, copy) NSString * __nonnull customIdentifier;
@property (nonatomic, readonly) NSMutableDictionary * __nonnull details;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithLatitude:(CLLocationDegrees)latitude longitude:(CLLocationDegrees)longitude radius:(double)radius customIdentifier:(NSString * __nonnull)customIdentifier;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithLocation:(Location * __nonnull)location radius:(double)radius customIdentifier:(NSString * __nonnull)customIdentifier OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * __nonnull)acoder;
@property (nonatomic, readonly, copy, getter=description) NSString * __nonnull description;
@end


SWIFT_CLASS("_TtC8SenseSdk21CustomGeofenceTrigger")
@interface CustomGeofenceTrigger : NSObject
@end


SWIFT_CLASS("_TtC8SenseSdk8Location")
@interface Location : NSObject
@property (nonatomic, readonly) CLLocationDegrees latitude;
@property (nonatomic, readonly) CLLocationDegrees longitude;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithLatitude:(CLLocationDegrees)latitude longitude:(CLLocationDegrees)longitude OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithLocation:(CLLocation * __nonnull)location OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * __nonnull)acoder;
- (CLLocationDistance)distanceFromLocation:(Location * __nonnull)loc;
- (CLLocationCoordinate2D)toCoordinate;
@property (nonatomic, readonly, copy, getter=description) NSString * __nonnull description;
- (CLLocationDistance)getDistance:(Location * __nonnull)other;
- (Location * __nonnull)addMetersToLatitude:(CLLocationDistance)distance;
- (Location * __nullable)getClosestLatLng:(NSArray * __nonnull)list;
@end


@interface NSArray (SWIFT_EXTENSION(SenseSdk))
@end


@interface NSDate (SWIFT_EXTENSION(SenseSdk))
@end


@interface NSFileManager (SWIFT_EXTENSION(SenseSdk))
@end


@interface NSNumber (SWIFT_EXTENSION(SenseSdk))
@end


@interface NSUserDefaults (SWIFT_EXTENSION(SenseSdk))
@end


SWIFT_CLASS("_TtC8SenseSdk17PersonalizedPlace")
@interface PersonalizedPlace : NSObject <NSCoding>
@property (nonatomic, readonly) Location * __nonnull location;
@property (nonatomic, readonly) double radius;
@property (nonatomic, readonly) NSMutableDictionary * __nonnull details;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * __nonnull)acoder;
@end


SWIFT_CLASS("_TtC8SenseSdk24PersonalizedPlaceTrigger")
@interface PersonalizedPlaceTrigger : NSObject
@end


SWIFT_CLASS("_TtC8SenseSdk8PoiPlace")
@interface PoiPlace : NSObject <NSCoding>
@property (nonatomic, readonly, copy) NSString * __nonnull id;
@property (nonatomic, readonly) Location * __nonnull location;
@property (nonatomic, readonly) double radius;
@property (nonatomic, readonly) NSMutableDictionary * __nonnull details;
@property (nonatomic, readonly, copy, getter=description) NSString * __nonnull description;
- (CLLocationDistance)distanceFrom:(Location * __nonnull)other;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * __nonnull)acoder;
@end


SWIFT_CLASS("_TtC8SenseSdk10PoiTrigger")
@interface PoiTrigger : NSObject
@end


SWIFT_CLASS("_TtC8SenseSdk6Recipe")
@interface Recipe : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull name;
@property (nonatomic, readonly) Cooldown * __nonnull cooldown;
@end

#pragma clang diagnostic pop
